services:
  ubuntu-server:
    image: mein_ubuntu
    container_name: ubuntu_1
    environment:
      - abc=example_value
    volumes:
      - D:\Schule\5BHET\AIIT\Docker\Docker_Zeug\Docker\ubuntu-server\compose\testdata:/test
    tty: true

