services:
  ubuntu-server:
    image: ubuntu:22.04
    container_name: ubuntu-server
    environment:
      - abc=example_value
    volumes:
      - D:\Schule\5BHET\AIIT\Docker\Docker_Zeug\Docker\ubuntu-server\compose\testdata:/test
    tty: true

