services:
  ubuntu-server:
    image: mein_ubuntu
    container_name: "${NAME:-ubuntu-name}"
    environment:
      - abc=${ENV_ABC:-example_value}
    volumes:
      - ${TEST_VOLUME}:/test
    tty: true

