services:
  apache:
    image: uebentest
    container_name: "${NAME:-uebentest}"
    environment:
      - APACHE_ADMIN=${EMAIL:-max@muster.at}
    volumes:
      - ${LOGDIR}:/var/log/apache2
      - ${WEBDIR}:/var/www/html
    ports:
      - 8087:80
    tty: true